version: '3'

services:
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./src/:/var/www/

  php:
    container_name: php
    build:
      context: ./php
    command: php-fpm -F
    volumes:
      - ./src/:/var/www/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini